--- 
- name: Examine syntax of yml files 
  hosts: clients 
  tasks: 
    - name: comments output 
      debug: 
        msg: Hellow There #This is a comment 
         #Also this a comment
         #
    
    - name: print a string with " " 
      debug: 
        msg: "This is a string" 

    - name: print a string with ' ' 
      debug: 
        msg: 'This is also a string'
    
    - name: print a lot of lines
      debug: 
        msg: |   #if you want print multiple lines use |(pipe) 
              this is the first line 
              this is the second line 
              etc.....

    - name: print a folded line 
      debug: 
        msg: > 
              this is an example 
              of the long sting 
              that will become one single line 

#Execute this playboot to check the syntax of each task in this play 
#Command is : #ansiable-playbook syntax.yml 


        
